sonar.projectKey=easyspot
sonar.projectName=EasySpot
sonar.sourceEncoding=UTF-8

sonar.sources=projX/web-easyspot/src,projX/api-easyspot/src/main/java
sonar.java.source=21
sonar.java.binaries=projX/api-easyspot/target/classes

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**
